jobs:
- job: ${{ parameters.arch }}
  pool: Fedora
  variables:
    #import parameters as variables from azure-pipelines.yml
    BUILD_ARCH: ${{ parameters.arch }}
    MOCK_ARCH: ${{ parameters.mock_arch }}
    BUILD_GIT: ${{ parameters.build_git }}
    BUILD_BRANCH: ${{ parameters.build_branch }}
    BUILD_SCRIPT: ${{ parameters.build_script }}
    BUILD_OPTS: ${{ parameters.build_opts }}
    BUILD_DEPS: ${{ parameters.build_deps }}
    TAR_DIR: ${{ parameters.tar_dir }}

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Cloning build script to '$(pwd)'/clone'
        git clone -b ${BUILD_BRANCH} ${BUILD_GIT} clone
    displayName: 'Cloning Build GitHub'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Running build script in '$(pwd)'/clone'
        sudo "echo $(pwd) && cd clone && ls -a && bash ${BUILD_SCRIPT} ${BUILD_OPTS}"
    displayName: 'Running Build Script'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: cp ./clone/${TAR_DIR}/install.tar.gz $(Build.ArtifactStagingDirectory)/install_$BUILD_ARCH_rootfs.tar.gz
    displayName: 'Copying .tar.gz to Artifacts'

